services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    volumes:
      - ./faiss_index:/app/faiss_index
      - ./assets:/app/assets
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    cpus: 1.0
    mem_limit: 512m
    mem_reservation: 256m
    command: python web_server.py