services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./faiss_index:/app/faiss_index
      - ./assets:/app/assets
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # cpus: 1.0
    # mem_limit: 512m
    # mem_reservation: 256m
    command: python web_server.py